routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/properti/beranda');
});
Route::name('front.')->group(function(){
    Route::prefix('properti')->group(function(){
		Route::get('/','FrontPropertiController@beranda')->name('beranda');
		Route::get('/beranda','FrontPropertiController@beranda')->name('beranda');

		Route::get('/properti-detail/{id}','FrontPropertiController@propertiDetail')->name('properti-detail');

    });
});



Route::middleware(['auth'])->group(function(){
	Route::name('administrator.')->group(function(){
	    Route::prefix('admin')->group(function(){

	    	Route::resource('beranda','administrator\BerandaAdminController');
	    	Route::resource('kategori', 'administrator\CategoriesController');
	    	Route::resource('penjual', 'administrator\PenjualController');
	    	Route::resource('properti', 'administrator\PropertiesController');
	    });
	});
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/kategori-add.blade.php
@extends('admin.master-page')
@section('content')
<div class="row">
    <div class="col-md-7 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-red-sunglo">
                    <i class="icon-settings font-red-sunglo"></i>
                    <span class="caption-subject bold uppercase"> Kategori Form</span>
                </div>
            </div>
            <div class="portlet-body form">
                <form action="{{route('administrator.kategori.store')}}" method="post">
                    @csrf
                    <div class="form-body">
                        <div class="form-group">
                            <label>Jenis Kategori</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-list-ul font-green"></i>
                                </span>
                                <input type="text" class="form-control" name="kategori" placeholder="Jenis Kategori"> </div>
                        </div>
                        <div class="form-group">
                            <label>Deskripsi</label>
                            <textarea class="form-control" rows="3" name="deskripsi"></textarea>
                        </div>
                    </div>
                    <div class="form-actions right">
                        <button type="reset" class="btn default">Cancel</button>
                        <button type="submit" class="btn green">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
</div
@endsection

resources/views/admin/kategori-edit.blade.php
@extends('admin.master-page')
@section('content')
<div class="row">
    <div class="col-md-7 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-red-sunglo">
                    <i class="icon-settings font-red-sunglo"></i>
                    <span class="caption-subject bold uppercase"> Kategori Form</span>
                </div>
            </div>
            <div class="portlet-body form">
                <form action="{{route('administrator.kategori.update',$kategori->id)}}" method="post">
                    @method('PUT')
                    @csrf
                    <div class="form-body">
                        <div class="form-group">
                            <label>Jenis Kategori</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-list-ul font-green"></i>
                                </span>
                                <input type="text" class="form-control" name="kategori" placeholder="Jenis Kategori" value="{{$kategori->kategori}}"> </div>
                        </div>
                        <div class="form-group">
                            <label>Deskripsi</label>
                            <textarea class="form-control" rows="3" name="deskripsi">{{$kategori->deskripsi}}</textarea>
                        </div>
                    </div>
                    <div class="form-actions right">
                        <button type="reset" class="btn default">Cancel</button>
                        <button type="submit" class="btn green">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
</div
@endsection

resources/views/admin/kategori.blade.php
@extends('admin.master-page')
@section('content')
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <a href="{{route('administrator.kategori.create')}}" class="btn btn-success"><i class="fa fa-plus mr-1"></i>Tambah Data</a>
                </div>
                <div class="tools"> </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover" id="sample_1">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Kategori</th>
                            <th>Deskripsi</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>No</th>
                            <th>Kategori</th>
                            <th>Deskripsi</th>
                            <th>Aksi</th>
                        </tr>
                    </tfoot>
                    <tbody>
                    @php ($i=1)
                    @foreach($kategori as $row)
                        <tr>
                            <td>{{$i}}</td>
                            <td>{{$row->kategori}}</td>
                            <td>{{$row->deskripsi}}</td>
                            <td>
                            <a href="{{route('administrator.kategori.edit',$row->id)}}" class="btn btn-warning">Edit</a>
                            <a class="btn btn-danger" href="{{route('administrator.kategori.destroy',$row->id)}}" onclick="event.preventDefault();
                                 document.getElementById('hapus-form').submit();">
                                Hapus
                            </a>
                            <form id="hapus-form" action="{{route('administrator.kategori.destroy',$row->id)}}" method="post" style="display: none;">
                            @method('delete')
                                            @csrf
                            </form>
                            
                            </td>
                        </tr>
                    @php ($i++)
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
        
    </div>
</div>
@endsection

resources/views/admin/master-menu.blade.php
<div class="page-sidebar-wrapper">
    <!-- BEGIN SIDEBAR -->
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <div class="page-sidebar navbar-collapse collapse">
        <!-- BEGIN SIDEBAR MENU -->
        <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
        <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
        <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
        <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
        <ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
            <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
            <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
            <li class="sidebar-toggler-wrapper hide">
                <div class="sidebar-toggler">
                    <span></span>
                </div>
            </li>
            <!-- END SIDEBAR TOGGLER BUTTON -->
            <!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
            <li class="sidebar-search-wrapper">
                <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
                <!-- DOC: Apply "sidebar-search-bordered" class the below search form to have bordered search box -->
                <!-- DOC: Apply "sidebar-search-bordered sidebar-search-solid" class the below search form to have bordered & solid search box -->
                <form class="sidebar-search  " action="page_general_search_3.html" method="POST">
                    <a href="javascript:;" class="remove">
                        <i class="icon-close"></i>
                    </a>
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <a href="javascript:;" class="btn submit">
                                <i class="icon-magnifier"></i>
                            </a>
                        </span>
                    </div>
                </form>
                <!-- END RESPONSIVE QUICK SEARCH FORM -->
            </li>
            <li class="nav-item <?php if($menu=='beranda'){?>active<?php }?> open">
                <a href="{{route('administrator.beranda.index')}}" class="nav-link nav-toggle">
                    <i class="icon-home"></i>
                    <span class="title">Dashboard</span>
                </a>
            </li>
            <li class="heading">
                <h3 class="uppercase">Menu</h3>
            </li>
            <li class="nav-item  <?php if($menu=='kategori'){?>active<?php }?>">
                <a href="{{route('administrator.kategori.index')}}" class="nav-link nav-toggle">
                    <i class="icon-settings"></i>
                    <span class="title">Kategori</span>
                </a>
            </li>
            <li class="nav-item  <?php if($menu=='penjual'){?>active<?php }?>">
                <a href="{{route('administrator.penjual.index')}}" class="nav-link nav-toggle">
                    <i class="fa fa-user"></i>
                    <span class="title">Penjual</span>
                </a>
            </li>
            <li class="nav-item  <?php if($menu=='properti'){?>active<?php }?>">
                <a href="{{route('administrator.properti.index')}}" class="nav-link nav-toggle">
                    <i class="fa fa-building"></i>
                    <span class="title">Properti</span>
                </a>
            </li>
            
            <li class="nav-item">
                <a href="javascript:;" class="nav-link nav-toggle">
                    <i class="icon-folder"></i>
                    <span class="title">Multi Level Menu</span>
                    <span class="arrow "></span>
                </a>
                <ul class="sub-menu">
                    <li class="nav-item">
                        <a href="javascript:;" class="nav-link nav-toggle">
                            <i class="icon-settings"></i> Item 1
                            <span class="arrow"></span>
                        </a>
                        <ul class="sub-menu">
                            <li class="nav-item">
                                <a href="javascript:;" target="_blank" class="nav-link">
                                    <i class="icon-user"></i> Arrow Toggle
                                    <span class="arrow nav-toggle"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item">
                                        <a href="#" class="nav-link">
                                            <i class="icon-power"></i> Sample Link 1</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#" class="nav-link">
                                            <i class="icon-paper-plane"></i> Sample Link 1</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="#" class="nav-link">
                                            <i class="icon-star"></i> Sample Link 1</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="icon-camera"></i> Sample Link 1</a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="icon-link"></i> Sample Link 2</a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="icon-pointer"></i> Sample Link 3</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="javascript:;" target="_blank" class="nav-link">
                            <i class="icon-globe"></i> Arrow Toggle
                            <span class="arrow nav-toggle"></span>
                        </a>
                        <ul class="sub-menu">
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="icon-tag"></i> Sample Link 1</a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="icon-pencil"></i> Sample Link 1</a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="icon-graph"></i> Sample Link 1</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="icon-bar-chart"></i> Item 3 </a>
                    </li>
                </ul>
            </li>
        </ul>
        <!-- END SIDEBAR MENU -->
        <!-- END SIDEBAR MENU -->
    </div>
    <!-- END SIDEBAR -->
</div>

resources/views/admin/penjual-add.blade.php
@extends('admin.master-page')
@section('content')
<div class="row">
    <div class="col-md-7 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-red-sunglo">
                    <i class="icon-settings font-red-sunglo"></i>
                    <span class="caption-subject bold uppercase"> Kategori Form</span>
                </div>
            </div>
            <div class="portlet-body form">
                <form action="{{route('administrator.penjual.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-body">
                        <div class="form-group">
                            <label>Nama</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-user font-green"></i>
                                </span>
                                <input type="text" class="form-control" name="nama" placeholder="Nama Lengkap"> </div>
                        </div>
                        <div class="form-group">
                            <label>NIK</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-credit-card font-green"></i>
                                </span>
                                <input type="text" class="form-control" name="nik" placeholder="NIK"> </div>
                        </div>
                                
                        <div class="row">
                            <div class="col-md-7">
                                <div class="form-group">
                                    <label>Tempat Lahir</label>
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="fa fa-map-marker font-green"></i>
                                        </span>
                                        <input type="text" class="form-control" name="tempat_lahir" placeholder="Tempat Lahir"> </div>
                                </div>
                            </div>
                            <div class="col-md-5">
                                <div class="form-group">
                                    <label>Tanggal Lahir</label>
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <i class="fa fa-calendar font-green"></i>
                                        </span>
                                        <input type="date" class="form-control" name="tanggal_lahir" placeholder="Tanggal Lahir"> </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Jenis Kelamin</label>
                            <select name="jenis_kelamin" class="form-control">
                                <option value="laki-laki">Laki-laki</option>
                                <option value="perempuan">Perempuan</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Pendidikan</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-graduation-cap font-green"></i>
                                </span>
                                <input type="text" name="pendidikan" class="form-control" placeholder="Pendidikan">
                            </div>
                        </div> 
                        <div class="form-group">
                            <label>Pekerjaan</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-user font-green"></i>
                                </span>
                                <input type="text" name="pekerjaan" class="form-control" placeholder="Pekerjaan">
                            </div>
                        </div> 
                        <div class="form-group">
                            <label>Telephone</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-mobile-phone font-green"></i>
                                </span>
                                <input type="text" name="telp" class="form-control" placeholder="Nomor Telephone">
                            </div>
                        </div>  
                        <div class="form-group">
                            <label>Photo</label>
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <i class="fa fa-photo font-green"></i>
                                </span>
                                <input type="file" name="poto" class="form-control" placeholder="Nomor Telephone">
                            </div>
                        </div>   
                        <div class="form-group">
                            <label>Alamat</label>
                            <textarea class="form-control" rows="3" name="alamat"></textarea>
                        </div>

                    </div>
                    <div class="form-actions right">
                        <button type="reset" class="btn default">Cancel</button>
                        <button type="submit" class="btn green">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->
    </div>
</div
@endsection

resources/views/admin/penjual.blade.php
@extends('admin.master-page')
@section('content')
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <a href="{{route('administrator.penjual.create')}}" class="btn btn-success"><i class="fa fa-plus mr-1"></i>Tambah Data</a>
                </div>
                <div class="tools"> </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover" id="sample_1">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama</th>
                            <th>NIK</th>
                            <th>Jenis Kelami</th>
                            <th>Telp</th>
                            <th>Alamat</th>
                            <th>Photo</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>No</th>
                            <th>Nama</th>
                            <th>NIK</th>
                            <th>Jenis Kelami</th>
                            <th>Telp</th>
                            <th>Alamat</th>
                            <th>Photo</th>
                            <th>Aksi</th>
                        </tr>
                    </tfoot>
                    <tbody>
                    @php ($i=1)
                    @foreach($penjual as $row)
                        <tr>
                            <td>{{$i}}</td>
                            <td>{{$row->nama}}</td>
                            <td>{{$row->nik}}</td>
                            <td>{{$row->jenis_kelamin}}</td>
                            <td>{{$row->telp}}</td>
                            <td>{{$row->alamat}}</td>
                            <td><img src="{{$row->poto}}"></td>
                            <td>
                            <a href="{{route('administrator.penjual.edit',$row->id)}}" class="btn btn-warning">Edit</a>
                            <a class="btn btn-danger" href="{{route('administrator.penjual.destroy',$row->id)}}" onclick="event.preventDefault();
                                 document.getElementById('hapus-form').submit();">
                                Hapus
                            </a>
                            <form id="hapus-form" action="{{route('administrator.penjual.destroy',$row->id)}}" method="post" style="display: none;">
                            @method('delete')
                                            @csrf
                            </form>
                            
                            </td>
                        </tr>
                    @php ($i++)
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
        
    </div>
</div>
@endsection

resources/views/admin/properti.blade.php
@extends('admin.master-page')
@section('content')
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <a href="{{route('administrator.properti.create')}}" class="btn btn-success"><i class="fa fa-plus mr-1"></i>Tambah Data</a>
                </div>
                <div class="tools"> </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover" id="sample_1">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Judul</th>
                            <th>Penjual</th>
                            <th>Kategori</th>
                            <th>Tipe</th>
                            <th>Harga</th>
                            <th>Alamat</th>
                            <th>Photo</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>No</th>
                            <th>Judul</th>
                            <th>Penjual</th>
                            <th>Kategori</th>
                            <th>Tipe</th>
                            <th>Harga</th>
                            <th>Alamat</th>
                            <th>Photo</th>
                            <th>Aksi</th>
                        </tr>
                    </tfoot>
                    <tbody>
                    @php ($i=1)
                    @foreach($properti as $row)
                        <tr>
                            <td>{{$i}}</td>
                            <td>{{$row->judul}}</td>
                            <td>{{$row->penjual_id}}</td>
                            <td>{{$row->kategori_id}}</td>
                            <td>{{$row->type}}</td>
                            <td>{{$row->harga}}</td>
                            <td>{{$row->alamat}}</td>
                            <td><img src="{{$row->poto}}"></td>
                            <td>
                            <a href="{{route('administrator.properti.edit',$row->id)}}" class="btn btn-warning"><i class="fa fa-pencil"></i> Edit</a>
                            <a class="btn btn-danger" href="{{route('administrator.properti.destroy',$row->id)}}" onclick="event.preventDefault();
                                 document.getElementById('hapus-form').submit();">
                               <i class="fa fa-times"></i> Hapus
                            </a>
                            <form id="hapus-form" action="{{route('administrator.properti.destroy',$row->id)}}" method="post" style="display: none;">
                            @method('delete')
                                            @csrf
                            </form>
                            
                            </td>
                        </tr>
                    @php ($i++)
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
        
    </div>
</div>
@endsection